// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset.sql

package database

import (
	"context"
)

const resetAllChirps = `-- name: ResetAllChirps :exec
DELETE FROM chirps
`

func (q *Queries) ResetAllChirps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAllChirps)
	return err
}

const resetAllUsers = `-- name: ResetAllUsers :exec
DELETE FROM users
`

func (q *Queries) ResetAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAllUsers)
	return err
}
